# Generated by Django 2.1.2 on 2018-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default='Untitled', max_length=180)),
                ('message', models.CharField(max_length=48)),
                ('total', models.IntegerField()),
                ('time_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(max_length=180)),
                ('content', models.CharField(default='Untitled', max_length=512)),
                ('count', models.IntegerField()),
                ('time_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(max_length=180)),
                ('message', models.CharField(max_length=48)),
                ('total', models.IntegerField()),
                ('weight', models.FloatField()),
                ('time_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(max_length=180)),
                ('content', models.CharField(default='Untitled', max_length=512)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
