# Generated by Django 2.1.2 on 2018-10-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxipy_api', '0003_jsonmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JSONModel',
            new_name='ChatText',
        ),
    ]
